1. Challenge 1:

- Answer: c
- Explanation: inside the function and then outside after we call the function

2. Challenge 2:

- Answer: c
- Explanation:

3. Challenge 3:

- Answer: c
- Explanation:

4. Challenge 4:

- Answer: 90
- Explanation: use the same reference

5. Bonus - Challenge 5:

- Answer: c
- Explanation: use the reference of rabbit 1 in rabbit2
