1. Challenge 1:
  - Answer: b) xyz, xyz
  - Explanation: The variable foo was updated within the function receiving xyz. When console.log is done the first time, xyz will appear because the variable had already been updated, and the same happens later in the second console.log because the variable no longer received any value other than xyz.


2. Challenge 2:
  - Answer: c 
  - Explanation: The "a" within the function executes initially and subsequently is replaced by the initial "a" in the global scope.



3. Challenge 3:
  - Answer: c
  - Explanation: The function can still be called.


4. Challenge 4:
  - Answer: c
  - Explanation:  When utilizing an object instead of a primitive data type, updating the stored value in "a" is necessary.


5. Bonus - Challenge 5:
  - Answer: c
  - Explanation:  The "rabbit one" persists unchanged, whereas "rabbit two" transforms into the object.
