1. Challenge 1:
  - Answer: b
  - Explanation: because foo inside the function  is not defined with let or const and in function scope


2. Challenge 2:
  - Answer: c
  - Explanation: because a is assigned inside the function and is replaced by 10.


3. Challenge 3:
  - Answer: c
  - Explanation: because it is normal function and even if sayHi() is assigned before it will work.


4. Challenge 4:
  - Answer: c
  - Explanation: because b = a and b.num = 90


5. Bonus - Challenge 5:
  - Answer:
  - Explanation:
